version: "3.8"

services:
  app:
    container_name: toft_app
    pull_policy: always
    image: ghcr.io/mathiasschoettle/tooloftools:main
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: toft

  mysql:
    container_name: toft_db
    image: ubuntu/mysql
    ports:
      - "3306:3306"
    volumes:
      - toft-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: toft

volumes:
  toft-mysql-data: